/**********************************************************************
 *                 gost_prov.c - The provider itself                  *
 *                                                                    *
 *      Copyright (c) 2021 Richard Levitte <richard@levitte.org>      *
 *     This file is distributed under the same license as OpenSSL     *
 *                                                                    *
 *                Requires OpenSSL 3.0 for compilation                *
 **********************************************************************/

#include <openssl/core_dispatch.h>
#include <openssl/core_names.h>
#include <openssl/crypto.h>
#include "gost_prov.h"
#include "gost_lcl.h"
#include "prov/err.h"           /* libprov err functions */

/*********************************************************************
 *
 *  Errors
 *
 *****/

/*
 * Ugly hack, to get the errors generated by mkerr.pl.  This should ideally
 * be replaced with a local OSSL_ITEM list of < number, string > pairs as
 * reason strings, but for now, we will simply use GOST_str_reasons.
 * Fortunately, the ERR_STRING_DATA structure is compatible with OSSL_ITEM,
 * so we can return it directly.
 */
static struct proverr_functions_st *err_handle;
#define GOST_PROV
#include "e_gost_err.c"
void ERR_GOST_error(int function, int reason, char *file, int line)
{
    proverr_new_error(err_handle);
    proverr_set_error_debug(err_handle, file, line, NULL);
    proverr_set_error(err_handle, reason, NULL);
}

/*********************************************************************
 *
 *  Provider context
 *
 *****/

static void provider_ctx_free(PROV_CTX *ctx)
{
    if (ctx != NULL) {
        ENGINE_free(ctx->e);
        proverr_free_handle(ctx->proverr_handle);
        OSSL_LIB_CTX_free(ctx->libctx);
    }
    OPENSSL_free(ctx);
}

extern int populate_gost_engine(ENGINE *e);
static PROV_CTX *provider_ctx_new(const OSSL_CORE_HANDLE *core,
                                  const OSSL_DISPATCH *in)
{
    PROV_CTX *ctx = NULL;

    if ((ctx = OPENSSL_zalloc(sizeof(*ctx))) == NULL)
        return NULL;

    ctx->core_handle = core;
    ctx->proverr_handle = proverr_new_handle(core, in);
    if (ctx->proverr_handle == NULL)
        goto err;

    ctx->libctx = OSSL_LIB_CTX_new_from_dispatch(core, in);
    if (ctx->libctx == NULL)
        ctx->libctx = OSSL_LIB_CTX_new();
    if (ctx->libctx == NULL)
        goto err;

    ctx->e = ENGINE_new();
    if (ctx->e == NULL || !populate_gost_engine(ctx->e))
        goto err;

    /* Ugly hack */
    err_handle = ctx->proverr_handle;
    return ctx;
 err:
    provider_ctx_free(ctx);
    return NULL;
}

/*********************************************************************
 *
 *  Setup
 *
 *****/

typedef void (*fptr_t)(void);

/* The function that returns the appropriate algorithm table per operation */
static const OSSL_ALGORITHM *gost_operation(void *vprovctx,
                                                int operation_id,
                                                const int *no_cache)
{
    const OSSL_ALGORITHM *ret = NULL;

    DEBUG_START();
    DEBUG_PARAM("operation_id=%d", operation_id);
    
    switch (operation_id) {
    case OSSL_OP_CIPHER:
        ret = GOST_prov_ciphers;
        break;
    case OSSL_OP_DIGEST:
        ret = GOST_prov_digests;
        break;
    case OSSL_OP_MAC:
        ret = GOST_prov_macs;
        break;
    case OSSL_OP_KEYMGMT:
        return GOST_prov_keymgmts;
    case OSSL_OP_ENCODER:
        return GOST_prov_encoders;
    case OSSL_OP_DECODER:
        return GOST_prov_decoders;
    }
    DEBUG_RESULT("ret=%p", ret);
    return ret;
}

static int gost_get_params(void *provctx, OSSL_PARAM *params)
{
    OSSL_PARAM *p;

    DEBUG_START();
    DEBUG_PARAM("provctx=%p", provctx);

    p = OSSL_PARAM_locate(params, OSSL_PROV_PARAM_NAME);
    if (p != NULL && !OSSL_PARAM_set_utf8_ptr(p, "OpenSSL GOST Provider"))
        {
            DEBUG_RESULT("failed setting %s", OSSL_PROV_PARAM_NAME);
            return 0;
        }
    p = OSSL_PARAM_locate(params, OSSL_PROV_PARAM_STATUS);
    if (p != NULL && !OSSL_PARAM_set_int(p, 1)) /* We never fail. */
        {
            DEBUG_RESULT("failed setting %s", OSSL_PROV_PARAM_STATUS);
            return 0;
        }

    DEBUG_RESULT("success");

    return 1;
}

static const OSSL_ITEM *gost_get_reason_strings(void *provctx)
{
#if 0
    return reason_strings;
#endif
    DEBUG_START();
    DEBUG_PARAM("provctx=%p", provctx);
    DEBUG_RESULT("returning GOST_str_reasons=%p", GOST_str_reasons);
    return (OSSL_ITEM *)GOST_str_reasons;
}

/* The function that tears down this provider */
static void gost_teardown(void *vprovctx)
{
    DEBUG_START();
    DEBUG_PARAM("provctx=%p", vprovctx);
    GOST_prov_deinit_ciphers();
    GOST_prov_deinit_digests();
    GOST_prov_deinit_mac_digests();
    provider_ctx_free(vprovctx);
    DEBUG_RESULT("teardown complete");
}

/* The base dispatch table */
static const OSSL_DISPATCH provider_functions[] = {
    { OSSL_FUNC_PROVIDER_QUERY_OPERATION, (fptr_t)gost_operation },
    { OSSL_FUNC_PROVIDER_GET_REASON_STRINGS, (fptr_t)gost_get_reason_strings },
    { OSSL_FUNC_PROVIDER_GET_PARAMS, (fptr_t)gost_get_params },
    { OSSL_FUNC_PROVIDER_TEARDOWN, (fptr_t)gost_teardown },
    { 0, NULL }
};

struct prov_ctx_st {
    void *core_handle;
    struct proverr_functions_st *err_handle;
};

#ifdef BUILDING_PROVIDER_AS_LIBRARY
/*
 * This allows the provider to be built in library form.  In this case, the
 * application must add it explicitly like this:
 *
 * OSSL_PROVIDER_add_builtin(NULL, "gost", GOST_provider_init);
 */
# define OSSL_provider_init GOST_provider_init
#endif

OPENSSL_EXPORT
int OSSL_provider_init(const OSSL_CORE_HANDLE *core,
                       const OSSL_DISPATCH *in,
                       const OSSL_DISPATCH **out,
                       void **vprovctx)
{
    int ret = 0;

    DEBUG_START();
    DEBUG_PARAM("core=%p", core);
    DEBUG_PARAM("in=%p", in);

    if ((*vprovctx = provider_ctx_new(core, in)) == NULL) {
        DEBUG_RESULT("provider_ctx_new failed");
        return 0;
    }
    *out = provider_functions;
    ret = 1;
    DEBUG_RESULT("out=%p provctx=%p ret=%d", *out, *vprovctx, ret);
    return ret;
}
